module.exports = {
  root: true,
  env: { browser: true, es2020: true, jest: true },
  extends: [
    'eslint:recommended',
    'plugin:react-hooks/recommended',
    'airbnb',
    'airbnb-base',
    'airbnb/hooks',
    'plugin:react/recommended',
    'prettier',
    'prettier/react',
    'plugin:prettier/recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
  ],
  ignorePatterns: ['dist', '.eslintrc.cjs'],
  parserOptions: { ecmaVersion: 'latest', sourceType: 'module' },
  settings: { react: { version: 'detect' } },
  plugins: ['react', 'react-hooks', 'prettier', 'react-refresh'],
  rules: {
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'warn',
    'react/prop-types': 'off',
    'import/no-import-module-exports': 0,
    'no-unused-expressions': 0,
    'import/no-unresolved': 0,
    'no-nested-ternary': 0,
    'global-require': 0,
    'arrow-parens': 0,
    'import/namespace': 0,
    'import/named': 0,
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
      },
    ],
    'prettier/prettier': 'error',
  },
  overrides: [
    {
      files: ['**/*.js', '**/*.jsx'],
      extends: [
        'eslint:recommended',
        'plugin:react/recommended',
        'plugin:import/errors',
        'plugin:import/warnings',
      ],
    },
  ],
};
